In [14]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_excel('问题二订购处理.xlsx')
data.head(10)

,供应商ID,第01周,第02周,第03周,第04周,第05周,第06周,第07周,第08周,第09周,...,第15周,第16周,第17周,第18周,第19周,第20周,第21周,第22周,第23周,第24周
0,S001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,S003,NaN,103.053818,103.053818,103.053818,103.053818,103.053818,103.053818,103.053818,103.053818,...,NaN,NaN,103.053818,NaN,103.053818,103.053818,103.053818,103.053818,NaN,103.053818
3,S004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,S005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,S006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,S007,NaN,45.057458,45.057458,45.057458,45.057458,NaN,NaN,45.057458,45.057458,...,45.057458,45.057458,NaN,45.057458,45.057458,45.057458,NaN,45.057458,45.057458,NaN
7,S008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,S009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,S010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data_ID = data['供应商ID']
data_week_1 = data['第01周']
data_week_1 = data_week_1[data_week_1.notnull()] # 删去非0行
data_week_1.head(10)

36      500.246877
85      127.438238
125     763.565539
142     558.800273
150    1433.761479
188      89.650683
200    2314.736747
209     134.893018
228    2569.927149
267     946.356250
Name: 第01周, dtype: float64